apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: demo-repo
  path: ./apps/webapp
  targetNamespace: web
  prune: true
  wait: true
