apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jheimar/flux-example.git
  ref:
    branch: main
